export const FETCH_ACTORS = 'FETCH_ACTORS';
export const SET_ACTORS = 'SET_ACTORS';
export const CLEAN_ACTORS = 'CLEAN_ACTORS'
export const SET_TOTAL_ACTORS_PAGES = 'SET_TOTAL_ACTORS_PAGES';

export const FETCH_ACTOR_CARD = 'FETCH_ACTOR_CARD';
export const SET_ACTOR_CARD = 'SET_ACTOR_CARD';
export const CLEAN_ACTOR_CARD = 'CLEAN_ACTOR_CARD';


export const INIT_SEARCH_ACTORS = 'INIT_SEARCH_ACTORS'
export const SEARCH_VALUE = 'SEARCH_VALUE'
