export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const CLEAN_MOVIES = 'CLEAN_MOVIES';
export const SET_TOTAL_MOVIES_PAGES = 'SET_TOTAL_MOVIES_PAGES';
export const IS_LOADING_MOVIES = 'IS_LOADING_MOVIES';

export const FETCH_MOVIE_CARD = 'FETCH_MOVIE_CARD';
export const SET_MOVIE_CARD = 'SET_MOVIE_CARD';
export const CLEAN_MOVIE_CARD = 'CLEAN_MOVIE_CARD';

export const INIT_SEARCH_MOVIES = 'INIT_SEARCH_MOVIES';
export const SEARCH_VALUE = 'SEARCH_VALUE';

